const navRoutes = {
    'portsmouth-property-maintenance': 'portsmouth-property-maintenance',
    'southsea-property-maintenance': 'southsea-property-maintenance',
    'cosham-property-maintenance': 'cosham-property-maintenance',
    'drayton-property-maintenance': 'drayton-property-maintenance',
    'farlington-property-maintenance': 'farlington-property-maintenance',
    'hilsea-property-maintenance': 'hilsea-property-maintenance',
    'fratton-property-maintenance': 'fratton-property-maintenance',
    'north-end-property-maintenance': 'north-end-property-maintenance',
    'milton-property-maintenance': 'milton-property-maintenance',
    'eastney-property-maintenance': 'eastney-property-maintenance',
    'paulsgrove-property-maintenance': 'paulsgrove-property-maintenance',
    'copnor-property-maintenance': 'copnor-property-maintenance',
    'widley-property-maintenance': 'widley-property-maintenance',
    'waterlooville-property-maintenance': 'waterlooville-property-maintenance',
    'purbrook-property-maintenance': 'purbrook-property-maintenance',
    'cowplain-property-maintenance': 'cowplain-property-maintenance',
    'denmead-property-maintenance': 'denmead-property-maintenance',
    'havant-property-maintenance': 'havant-property-maintenance',
    'bedhampton-property-maintenance': 'bedhampton-property-maintenance',
    'leigh-park-property-maintenance': 'leigh-park-property-maintenance',
    'emsworth-property-maintenance': 'emsworth-property-maintenance',
    'hayling-island-property-maintenance': 'hayling-island-property-maintenance',
    'horndean-property-maintenance': 'horndean-property-maintenance',
    'rowlands-castle-property-maintenance': 'rowlands-castle-property-maintenance',
    'petersfield-property-maintenance': 'petersfield-property-maintenance',
    'fareham-property-maintenance': 'fareham-property-maintenance',
    'gosport-property-maintenance': 'gosport-property-maintenance',
    'stubbington-property-maintenance': 'stubbington-property-maintenance',
    'titchfield-property-maintenance': 'titchfield-property-maintenance',
    'wickham-property-maintenance': 'wickham-property-maintenance',
    'bishop-waltham-property-maintenance': 'bishop-waltham-property-maintenance',
    'porchester-property-maintenance': 'porchester-property-maintenance',
    'portsmouth-handyman': 'portsmouth-handyman',
    'southsea-handyman': 'southsea-handyman',
    'waterlooville-handyman': 'waterlooville-handyman',
    'fareham-handyman': 'fareham-handyman',
    'gosport-handyman': 'gosport-handyman',
    'havant-handyman': 'havant-handyman'
};

module.exports = navRoutes;
